import type { Customer } from "../interfaces/customer.interface"

export const MOCK_CUSTOMERS: Customer[] = [
  {
    id: "cust_1",
    name: "شركة الإنشاءات المتحدة",
    email: "info@unitedconstruction.com",
    phone: "+966 11 234 5678",
    addresses: [
      {
        street: "شارع الملك فهد",
        city: "الرياض",
        state: "منطقة الرياض",
        postalCode: "12345",
        country: "المملكة العربية السعودية",
      },
    ],
    orders: ["ord_1"],
    totalSpent: 78500,
    createdAt: new Date("2023-01-10"),
    updatedAt: new Date("2024-05-05"),
  },
  {
    id: "cust_2",
    name: "مؤسسة البناء الحديث",
    email: "contact@modernbuilding.com",
    phone: "+966 12 345 6789",
    addresses: [
      {
        street: "شارع الأمير سلطان",
        city: "جدة",
        state: "منطقة مكة المكرمة",
        postalCode: "23456",
        country: "المملكة العربية السعودية",
      },
    ],
    orders: ["ord_2"],
    totalSpent: 15000,
    createdAt: new Date("2023-02-15"),
    updatedAt: new Date("2024-05-12"),
  },
  {
    id: "cust_3",
    name: "شركة الخليج للمقاولات",
    email: "info@gulfcontracting.com",
    phone: "+966 13 456 7890",
    addresses: [
      {
        street: "طريق الملك عبدالعزيز",
        city: "الدمام",
        state: "المنطقة الشرقية",
        postalCode: "34567",
        country: "المملكة العربية السعودية",
      },
    ],
    orders: ["ord_3"],
    totalSpent: 40700,
    createdAt: new Date("2023-03-20"),
    updatedAt: new Date("2024-05-16"),
  },
  {
    id: "cust_4",
    name: "مؤسسة النهضة للتعمير",
    email: "projects@nahda.com",
    phone: "+966 11 567 8901",
    addresses: [
      {
        street: "شارع الستين",
        city: "الرياض",
        state: "منطقة الرياض",
        postalCode: "12345",
        country: "المملكة العربية السعودية",
      },
    ],
    orders: ["ord_4"],
    totalSpent: 45000,
    createdAt: new Date("2023-04-25"),
    updatedAt: new Date("2024-05-20"),
  },
  {
    id: "cust_5",
    name: "شركة الإعمار الدولية",
    email: "info@international-construction.com",
    phone: "+966 12 678 9012",
    addresses: [
      {
        street: "طريق المدينة",
        city: "جدة",
        state: "منطقة مكة المكرمة",
        postalCode: "23456",
        country: "المملكة العربية السعودية",
      },
    ],
    orders: ["ord_5"],
    totalSpent: 120000,
    createdAt: new Date("2023-05-30"),
    updatedAt: new Date("2024-05-27"),
  },
  {
    id: "cust_6",
    name: "مؤسسة الفارس للمقاولات",
    email: "info@alfaris.com",
    phone: "+966 14 789 0123",
    addresses: [
      {
        street: "شارع الملك خالد",
        city: "بريدة",
        state: "منطقة القصيم",
        postalCode: "45678",
        country: "المملكة العربية السعودية",
      },
    ],
    orders: [],
    totalSpent: 0,
    createdAt: new Date("2023-06-15"),
    updatedAt: new Date("2023-06-15"),
  },
  {
    id: "cust_7",
    name: "شركة البناء الأخضر",
    email: "contact@greenbuilding.com",
    phone: "+966 11 890 1234",
    addresses: [
      {
        street: "طريق الملك سلمان",
        city: "الرياض",
        state: "منطقة الرياض",
        postalCode: "12345",
        country: "المملكة العربية السعودية",
      },
    ],
    orders: [],
    totalSpent: 0,
    createdAt: new Date("2023-07-20"),
    updatedAt: new Date("2023-07-20"),
  },
  {
    id: "cust_8",
    name: "مؤسسة الصفوة للتطوير العقاري",
    email: "info@safwa-dev.com",
    phone: "+966 12 901 2345",
    addresses: [
      {
        street: "شارع فلسطين",
        city: "جدة",
        state: "منطقة مكة المكرمة",
        postalCode: "23456",
        country: "المملكة العربية السعودية",
      },
    ],
    orders: [],
    totalSpent: 0,
    createdAt: new Date("2023-08-25"),
    updatedAt: new Date("2023-08-25"),
  },
]
