import type { Order } from "../interfaces/order.interface"

export const MOCK_ORDERS: Order[] = [
  {
    id: "ord_1",
    orderNumber: "ORD-20240501",
    customerId: "cust_1",
    customerName: "شركة الإنشاءات المتحدة",
    customerEmail: "info@unitedconstruction.com",
    status: "delivered",
    total: 78500,
    items: [
      {
        productId: "prod_2",
        productName: "جرافة متوسطة الحجم",
        quantity: 1,
        unitPrice: 78500,
        total: 78500,
      },
    ],
    shippingAddress: {
      street: "شارع الملك فهد",
      city: "الرياض",
      state: "منطقة الرياض",
      postalCode: "12345",
      country: "المملكة العربية السعودية",
    },
    billingAddress: {
      street: "شارع الملك فهد",
      city: "الرياض",
      state: "منطقة الرياض",
      postalCode: "12345",
      country: "المملكة العربية السعودية",
    },
    paymentMethod: "تحويل بنكي",
    createdAt: new Date("2024-05-01"),
    updatedAt: new Date("2024-05-05"),
  },
  {
    id: "ord_2",
    orderNumber: "ORD-20240510",
    customerId: "cust_2",
    customerName: "مؤسسة البناء الحديث",
    customerEmail: "contact@modernbuilding.com",
    status: "shipped",
    total: 15000,
    items: [
      {
        productId: "prod_5",
        productName: "خلاطة إسمنت صغيرة",
        quantity: 1,
        unitPrice: 15000,
        total: 15000,
      },
    ],
    shippingAddress: {
      street: "شارع الأمير سلطان",
      city: "جدة",
      state: "منطقة مكة المكرمة",
      postalCode: "23456",
      country: "المملكة العربية السعودية",
    },
    billingAddress: {
      street: "شارع الأمير سلطان",
      city: "جدة",
      state: "منطقة مكة المكرمة",
      postalCode: "23456",
      country: "المملكة العربية السعودية",
    },
    paymentMethod: "بطاقة ائتمان",
    createdAt: new Date("2024-05-10"),
    updatedAt: new Date("2024-05-12"),
  },
  {
    id: "ord_3",
    orderNumber: "ORD-20240515",
    customerId: "cust_3",
    customerName: "شركة الخليج للمقاولات",
    customerEmail: "info@gulfcontracting.com",
    status: "processing",
    total: 40700,
    items: [
      {
        productId: "prod_8",
        productName: "آلة لحام احترافية",
        quantity: 2,
        unitPrice: 4200,
        total: 8400,
      },
      {
        productId: "prod_7",
        productName: "مضخة مياه قوية",
        quantity: 1,
        unitPrice: 8500,
        total: 8500,
      },
      {
        productId: "prod_10",
        productName: "ضاغط هواء كبير",
        quantity: 1,
        unitPrice: 12500,
        total: 12500,
      },
      {
        productId: "prod_6",
        productName: "مولد كهربائي متوسط",
        quantity: 1,
        unitPrice: 28000,
        total: 28000,
      },
    ],
    shippingAddress: {
      street: "طريق الملك عبدالعزيز",
      city: "الدمام",
      state: "المنطقة الشرقية",
      postalCode: "34567",
      country: "المملكة العربية السعودية",
    },
    billingAddress: {
      street: "طريق الملك عبدالعزيز",
      city: "الدمام",
      state: "المنطقة الشرقية",
      postalCode: "34567",
      country: "المملكة العربية السعودية",
    },
    paymentMethod: "تحويل بنكي",
    createdAt: new Date("2024-05-15"),
    updatedAt: new Date("2024-05-16"),
  },
  {
    id: "ord_4",
    orderNumber: "ORD-20240520",
    customerId: "cust_4",
    customerName: "مؤسسة النهضة للتعمير",
    customerEmail: "projects@nahda.com",
    status: "pending",
    total: 45000,
    items: [
      {
        productId: "prod_1",
        productName: "حفارة هيدروليكية صغيرة",
        quantity: 1,
        unitPrice: 45000,
        total: 45000,
      },
    ],
    shippingAddress: {
      street: "شارع الستين",
      city: "الرياض",
      state: "منطقة الرياض",
      postalCode: "12345",
      country: "المملكة العربية السعودية",
    },
    billingAddress: {
      street: "شارع الستين",
      city: "الرياض",
      state: "منطقة الرياض",
      postalCode: "12345",
      country: "المملكة العربية السعودية",
    },
    paymentMethod: "بطاقة ائتمان",
    createdAt: new Date("2024-05-20"),
    updatedAt: new Date("2024-05-20"),
  },
  {
    id: "ord_5",
    orderNumber: "ORD-20240525",
    customerId: "cust_5",
    customerName: "شركة الإعمار الدولية",
    customerEmail: "info@international-construction.com",
    status: "cancelled",
    total: 120000,
    items: [
      {
        productId: "prod_4",
        productName: "شاحنة نقل كبيرة",
        quantity: 1,
        unitPrice: 120000,
        total: 120000,
      },
    ],
    shippingAddress: {
      street: "طريق المدينة",
      city: "جدة",
      state: "منطقة مكة المكرمة",
      postalCode: "23456",
      country: "المملكة العربية السعودية",
    },
    billingAddress: {
      street: "طريق المدينة",
      city: "جدة",
      state: "منطقة مكة المكرمة",
      postalCode: "23456",
      country: "المملكة العربية السعودية",
    },
    paymentMethod: "تحويل بنكي",
    createdAt: new Date("2024-05-25"),
    updatedAt: new Date("2024-05-27"),
  },
]
