import type { Product } from "../interfaces/product.interface"

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "prod_1",
    name: "حفارة هيدروليكية صغيرة",
    description: "حفارة هيدروليكية صغيرة للاستخدامات المتعددة",
    price: 45000,
    category: "حفارات",
    stock: 12,
    sku: "EXC-S-001",
    imageUrl: "/assets/images/products/excavator-small.jpg",
    status: "active",
    createdAt: new Date("2023-01-15"),
    updatedAt: new Date("2023-06-20"),
  },
  {
    id: "prod_2",
    name: "جرافة متوسطة الحجم",
    description: "جرافة متوسطة الحجم مناسبة للمشاريع المتوسطة",
    price: 78500,
    category: "جرافات",
    stock: 8,
    sku: "BUL-M-002",
    imageUrl: "/assets/images/products/bulldozer-medium.jpg",
    status: "active",
    createdAt: new Date("2023-02-10"),
    updatedAt: new Date("2023-07-05"),
  },
  {
    id: "prod_3",
    name: "رافعة شوكية ثقيلة",
    description: "رافعة شوكية للأحمال الثقيلة بقدرة رفع عالية",
    price: 62000,
    category: "رافعات",
    stock: 0,
    sku: "FOR-H-003",
    imageUrl: "/assets/images/products/forklift-heavy.jpg",
    status: "out_of_stock",
    createdAt: new Date("2023-03-05"),
    updatedAt: new Date("2023-08-15"),
  },
  {
    id: "prod_4",
    name: "شاحنة نقل كبيرة",
    description: "شاحنة نقل كبيرة للمواقع الإنشائية",
    price: 120000,
    category: "شاحنات",
    stock: 5,
    sku: "TRU-L-004",
    imageUrl: "/assets/images/products/truck-large.jpg",
    status: "active",
    createdAt: new Date("2023-04-20"),
    updatedAt: new Date("2023-09-10"),
  },
  {
    id: "prod_5",
    name: "خلاطة إسمنت صغيرة",
    description: "خلاطة إسمنت صغيرة للمشاريع الصغيرة",
    price: 15000,
    category: "خلاطات",
    stock: 20,
    sku: "MIX-S-005",
    imageUrl: "/assets/images/products/mixer-small.jpg",
    status: "active",
    createdAt: new Date("2023-05-12"),
    updatedAt: new Date("2023-10-01"),
  },
  {
    id: "prod_6",
    name: "مولد كهربائي متوسط",
    description: "مولد كهربائي متوسط الحجم للمواقع الإنشائية",
    price: 28000,
    category: "مولدات",
    stock: 15,
    sku: "GEN-M-006",
    imageUrl: "/assets/images/products/generator-medium.jpg",
    status: "active",
    createdAt: new Date("2023-06-08"),
    updatedAt: new Date("2023-11-15"),
  },
  {
    id: "prod_7",
    name: "مضخة مياه قوية",
    description: "مضخة مياه قوية لتصريف المياه من مواقع البناء",
    price: 8500,
    category: "مضخات",
    stock: 25,
    sku: "PUM-P-007",
    imageUrl: "/assets/images/products/pump-powerful.jpg",
    status: "active",
    createdAt: new Date("2023-07-22"),
    updatedAt: new Date("2023-12-05"),
  },
  {
    id: "prod_8",
    name: "آلة لحام احترافية",
    description: "آلة لحام احترافية للاستخدامات الصناعية",
    price: 4200,
    category: "معدات لحام",
    stock: 18,
    sku: "WEL-P-008",
    imageUrl: "/assets/images/products/welder-pro.jpg",
    status: "active",
    createdAt: new Date("2023-08-14"),
    updatedAt: new Date("2024-01-10"),
  },
  {
    id: "prod_9",
    name: "منشار كهربائي صناعي",
    description: "منشار كهربائي صناعي لقطع المواد الصلبة",
    price: 3800,
    category: "معدات قطع",
    stock: 0,
    sku: "SAW-I-009",
    imageUrl: "/assets/images/products/saw-industrial.jpg",
    status: "out_of_stock",
    createdAt: new Date("2023-09-05"),
    updatedAt: new Date("2024-02-20"),
  },
  {
    id: "prod_10",
    name: "ضاغط هواء كبير",
    description: "ضاغط هواء كبير للاستخدامات الصناعية",
    price: 12500,
    category: "ضواغط",
    stock: 7,
    sku: "COM-L-010",
    imageUrl: "/assets/images/products/compressor-large.jpg",
    status: "active",
    createdAt: new Date("2023-10-18"),
    updatedAt: new Date("2024-03-05"),
  },
]
